server:
  port: 8000
  servlet:
#   기존 context-path = /
    context-path: /springprojectblog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
#      prefix는 앞에 붙여주는 경로
      prefix: /WEB-INF/views/
#      suffix는 뒤에 붙여주는 경로
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:{데이터 베이스 주소}:{포트번호}/{스키마명}
    username: {username}
    password: {password}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
    
# 들여쓰기는 띄여쓰기 2번
